export const LOGIN = '/user/login',
  REGISTER = '/user/register',
  LIST_VIRTUEL_MACHINES = '/manage/listVms',
  HOST_VIRTUEL_MACHINE = '/manage/hostVm',
  UNLINK_VIRTUEL_MACHINE = '/manage/unlinkVm',
  START_VIRTUEL_MACHINE = '/manage/startVm',
  GET_VIRTUEL_MACHINES = '/manage/getAllHostedVms',
  GET_VIRTUEL_MACHINE_BY_IP = '/manage/getVmStatusByIp',
  CONFIGURE_SERVICE_ACCOUNT = '/manage/configureServiceAccount';
